language: objective-c
osx_image: xcode7.1
install: script/install-dependencies.sh
before_script:
- chmod +x script/add-key.sh
- chmod +x script/remove-key.sh
- chmod +x script/sign-and-upload.sh
- chmod +x script/update-bundle.sh
- chmod +x script/build.sh
- "./script/add-key.sh"
- "./script/update-bundle.sh"
script:
- "./script/build.sh"
after_success:
- "./script/sign-and-upload.sh"
after_script:
- "./script/remove-key.sh"
env:
  global:
  - APP_NAME="iPad"
  - 'DEVELOPER_NAME="iPhone Distribution: Teknologi Kreasi Anak Bangsa, PT (A9P9DCV3NU)"'
  - PROFILE_NAME="Urbanindo_Adhoc_iPad"
  - INFO_PLIST="iPad/Info.plist"
  - BUNDLE_DISPLAY_NAME="iPad"
  - secure: Smcn3KKWeOinijiORi/WxCfJeOf17LJKSb7DUKTSc6GRAvB5z6iGrk84oGxmKJ+CjN/qEWWL5JfsXlGHpKAGUA7eVlg/RJ+j3ZLLU2IrgSenKpAj/Rc600RXFIosciNMJbDDm0oWwYJVIdMKEwYIevn80UBegFel4f8pGGqqlzN+C3SAhlbNY8VCUTD5MLTtUAddY6S6nSGMz5NWjH/salYwlhbay8Y93MUzSB0oGPlgQgplPNYlcQFADnvyQDAeBRkG4Gf89+HZW2o2PR1bA+oQbPu079XMTvJrtLbyU0qe1zu9II430xOdgw+h/kbTu3ed9TX4qLWzW08SGAPgBhK9tdItkuN8qTprfklNKDoYLIBVFhYsCiTFLAN8KmgyB/vpEQLTNGFwFa0ePr8TmnnlqH27lLz+sESWm8Hg8//9YC1TMZseqbWF6WNphEGOBctK+XwS0RkEPC6n0LjNFpSreh70fDAbqBvoxn4B2mFlCYfXQ0j2BM51VMKqPLtykC1Z36Rl8B+Dawd+MoUdw7YGQdOgsgQD8xDC8h67uEwhMmEJ5cmUiYAsnzxyBp8l+OuXVZSP9X85q93+09FmW7eo1KJt0ZKQ1xP0l0qujZNNNmtSL/jAJCtI5RcL5BnSa/FuzwitxdUMJpNx9xp2ygsu45Zg9WcqnYkExsvpAMY=
  - secure: QKeAsDAs2zfCLhwfWwcvZnzQz/X3kHjH/R+wHhjUTVJZemYRGqtPJgTw7EZ8+ntiS4mkmanEI7SuDsJuM1oYhxesW3JREyeeH7QruD39Zn4fKi3W2g0atlX4oJzDIYmSejGVptdYBiatY1yWdNO1hkIvfMct4A9RkwWq/6Y3UEkR54oU2Rs4p9GFscYsni219DkgvMBSUFE+AiC88sceVTvqcXzgEueGDK8gCieMV6iYJvpdjxJ4Hh//h/iP0Tg5tja8KJBYkMICB6HzRd5uhvg+nhWqI4l0m7nFLAq/1s5P4+Z7oMqQVbOzPwG/W8njIuWfg56kanOHaPCtgMqBumNo+N6G/hdQHLCx0QMsPYkE87wivmMp23Fr6nJehqfBt9yGK4UKiTmJjhTVAQn+AHlcoNlf0NABJnycQvN2pDl0uO/QmTc8x0rolHaysGnR1IceDq1Non0BIzTfI8RUtSm1FyfTvLGblM+0wPd95o+4UauWuEhkO5AWifG5dv4eDCntTQvz4wgWXsIoTu/Unjl3AkyjQ4Om9P9clB0XI3ks699Ppltn9x9yP0dJeZXswll4lKg9euO+LgFKYe3xHG8VtwqQvY5L6WsMjOWHE1WJfFq8gjbV6FCBfL8ZuAbhfgALn8jBs/S0SfbD2UuevnkDAjzt6l7eJMgRrFKJmxo=
  - secure: QCZjOG10+qk2JgixpdW91TnSslByJ73zIrk/+23WKt/kaxPWGnTg7k8yVz3iqrxAqc8jmI23DNY97FLj0FQRH1l5mOjz4cB7FyBktVby1ULIp272P/8F9LLoPRLOZbH85gHsW5F1SiS9vGMueQame6+kevb9g7P7tR910jsuGgOemqucFBbKxNJPzGTt6fm0XNlZAkfoEvkERkVWpvzXexysR0RWt7FqGV6WyL8VtojlH3QV9+ELRIwGWEzGD/xPaw5I1mzKsCJt4g08RNQtr25sbuAp5/e6wINSlOzKHdi2jisYvhMoV63MUZqzhMilmP7y3rOYfgk//BCeaJlICy8xExBkSVCXhN7O6OKPNgjPh6cWxlYxueVEjvBN4zFm+ihEvJQ44Rwt7cICpTFlSoEj7bfO6Gx1Qn3xiqVB9Sevo0Z8x1a9SkzBaRErNZS6/ZnKUrLNcobtf0pJXXSx1nQ0BbAYfALb2Z+JtMDMziNj8DTv2AnhrSuyeOc08eVQnjBhavSblr6enEH7eSxFjeeNZFd4K4Yzk1qlUv/mzJgyhX43XvgstkLQeOfz5+3z+dF13BH9RevmTEfv1EapYOAEeR3J41gHM/RLSkR4Q6PEkUzVvh6baWhp4tAIq9ula5HY4W/2V9Cn0OU/mI8rsKgPtGcWs3+Z4oHO2WiV3ig=
